### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by feiyangwei** [alafighting/CharacterPickerView#11]
设置属性为循环，只要数据数目<=3，就会提示数组越界

**Comment by imkarl** [comment]
方便贴一下错误日志吗？非常感谢！

**Comment by feiyangwei** [comment]
属性设置为循环
你可以直接将第二部分的数据数目设置为3个，测试
这是我的错误日志
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
at java.util.ArrayList.get(ArrayList.java:306)
at LoopView.onDraw(LoopView.java:276)
at android.view.View.draw(View.java:13740)
at android.view.View.buildDrawingCache(View.java:12994)
at android.view.View.getDisplayList(View.java:12649)
at android.view.View.getDisplayList(View.java:12714)
at android.view.View.draw(View.java:13456)
at android.view.ViewGroup.drawChild(ViewGroup.java:2964)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2833)
at android.view.View.getDisplayList(View.java:12668)
at android.view.View.getDisplayList(View.java:12714)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2946)

**Comment by feiyangwei** [comment]
参考了这个
https://github.com/saiwu-bigkoo/Android-PickerView.git
对比了一下没发现有什么区别，但是那个是好的

**Comment by imkarl** [comment]
本项目是在https://github.com/saiwu-bigkoo/Android-PickerView.git 基础上简化调用，以及一些UI微调。
该作者有经常更新，你也可以考虑哪个更适合你的需求。

以上bug晚点会修复，但这两天比较忙，没时间处理

**Comment by imkarl** [comment]
代码已升级，请确认是否已修复你遇到的问题。

**Comment by feiyangwei** [comment]
嗯，没问题了，灰常感谢
