### ISSUE TITLE
混淆规则怎么设置？

### ISSUE THREAD

**Issue by XuQK** [alafighting/CharacterPickerView#20]
混淆后报错

```java
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@8d24df1
versionCode=1
BOARD=hammerhead
BOOTLOADER=HHZ20h
TYPE=user
ID=M4B30X
TIME=1472688361000
BRAND=google
TAG=Build
SERIAL=068befde003c6e4e
HARDWARE=hammerhead
SUPPORTED_ABIS=[Ljava.lang.String;@eb0cdd6
CPU_ABI=armeabi-v7a
RADIO=M8974A-2.0.50.2.30
IS_DEBUGGABLE=false
MANUFACTURER=LGE
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@625a198
TAGS=release-keys
CPU_ABI2=armeabi
UNKNOWN=unknown
USER=android-build
FINGERPRINT=google/hammerhead/hammerhead:6.0.1/M4B30X/3237893:user/release-keys
HOST=vpec7.mtv.corp.google.com
PRODUCT=hammerhead
versionName=1.0
DISPLAY=M4B30X
MODEL=Nexus 5
DEVICE=hammerhead
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at com.bigkoo.pickerview.lib.WheelView.void measureTextWidthHeight()(SourceFile:250)
	at com.bigkoo.pickerview.lib.WheelView.void remeasure()(SourceFile:217)
	at com.bigkoo.pickerview.lib.WheelView.void setAdapter(com.bigkoo.pickerview.adapter.WheelAdapter)(SourceFile:328)
	at com.bigkoo.pickerview.view.WheelOptions.void setPicker(java.util.List,java.util.List,java.util.List)(SourceFile:68)
	at com.bigkoo.pickerview.OptionsPickerView.void setPicker(java.util.List,java.util.List,java.util.List)(SourceFile:522)
	at com.hulixuehui.app.ui.login.RegisterActivity.void selectCity(java.util.List,java.util.List,java.util.List)(SourceFile:101)
	at com.hulixuehui.app.ui.login.RegisterViewModel.void selectCity(android.view.View)(SourceFile:129)
	at com.hulixuehui.app.databinding.ActivityRegisterBinding$OnClickListenerImpl.void onClick(android.view.View)(SourceFile:694)
	at android.view.View.performClick(View.java:5204)
	at android.view.View$PerformClick.run(View.java:21153)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

**Comment by XuQK** [comment]
发错地方了。。不好意思
